[book]
authors = ["robopandas"]
language = "en"
multilingual = false
src = "src"
title = "The Cookbook"

[output.html.code.hidelines]
java = "# "
kt = "# "

[output.html]
mathjax-support = true
site-url = "/cookbook/"
git-repository-url = "https://github.com/dr-hextanium/cookbook/tree/main"
edit-url-template = "https://github.com/dr-hextanium/cookbook/tree/main/{path}"
